<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_EthDevice" Id="{c11f7280-27ca-4f3d-865b-a554dd255326}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_EthDevice
VAR_INPUT
	bEnable		: BOOL 			:= FALSE;				(* TRUE => enable client data exchange, FALSE => disable *)
	sSrvNetID	: T_AmsNetID	:= '';					(* TwinCAT TCP/IP server network address *)
	sRemoteHost	: T_IPv4Addr 	:= '127.0.0.1';			(* Server network address *)
	nRemotePort	: UDINT 		:= 200;					(* Server port number *)
	bLogEnable	: BOOL 			:= FALSE;				(* TRUE => Enable log message output, FALSE => Disable *)
	sLogPrefix	: STRING 		:= 'CLIENT::';			(* Log message description string (allows the identification of log message source) *)
END_VAR
VAR_OUTPUT
	sData						: T_MaxString;			(* Output received Data *)
	bConnected					: BOOL := FALSE;		(* TCP/IP connection state *)	
END_VAR
VAR
	fbConnection				: FB_ClientConnection;	(* Client connection/data exchange control function block *)
	fbTx 						: FB_FrameFifo;			(* Tx fifo *)
	fbRx 						: FB_FrameFifo;			(* Rx fifo *)
	
	sLogMessage					: T_MaxString;
	sTemData					: T_MaxString;			(* Output received Data *)
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF bConnected := fbConnection.bConnected THEN
	A_Receive();
END_IF

A_Call();

IF NOT fbConnection.RxBusy THEN
	sData := sTemData;
END_IF]]></ST>
    </Implementation>
    <Action Name="A_Call" Id="{9bbcadd1-063f-4649-8065-66483265221a}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"FB_ClientConnection"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"fbConnection"</v>
                          <v n="Type">"FB_ClientConnection"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">51L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems">
                            <n />
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"fbTx"</v>
                              <v n="Type">"FB_FrameFifo"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                            <v n="Id">4L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"fbRx"</v>
                              <v n="Type">"FB_FrameFifo"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">7L</v>
                            </o>
                            <v n="Id">6L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sSrvNetID"</v>
                              <v n="Type">"T_AmsNetID"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">13L</v>
                            </o>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sRemoteHost"</v>
                              <v n="Type">"T_IPv4Addr"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">15L</v>
                            </o>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"nRemotePort"</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">17L</v>
                            </o>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"bEnable"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">19L</v>
                            </o>
                            <v n="Id">18L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#5s"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">21L</v>
                            </o>
                            <v n="Id">20L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#10ms"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">48L</v>
                            </o>
                            <v n="Id">47L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#500ms"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">50L</v>
                            </o>
                            <v n="Id">49L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>fbTx</v>
                            <v>fbRx</v>
                            <v>sSrvNetID</v>
                            <v>sRemoteHost</v>
                            <v>nRemotePort</v>
                            <v>bEnable</v>
                            <v>tReconnect</v>
                            <v>tPoll</v>
                            <v>tResponse</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>FB_FrameFifo[REF]</v>
                            <v>FB_FrameFifo[REF]</v>
                            <v>T_AmsNetID</v>
                            <v>T_IPv4Addr</v>
                            <v>UDINT</v>
                            <v>BOOL</v>
                            <v>TIME</v>
                            <v>TIME</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>bConnected</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">52L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="A_Receive" Id="{44b562d5-7166-4ed6-8902-d98806e6705c}">
      <Implementation>
        <ST><![CDATA[	(*--------------------- Get received message strings --------------------------------*)
	REPEAT
		fbRx.RemoveHead( );(* Fetch string from rx fifo *)
		IF fbRx.bOk THEN(* Success *)
	
		(* TODO: Implement receive data handler *)
			sTemData := fbRx.sGet; 		
			
		END_IF
	UNTIL NOT fbRx.bOk
	END_REPEAT
]]></ST>
      </Implementation>
    </Action>
    <Method Name="Send" Id="{6d0fdf11-2b9c-45c0-94d0-44e8e8ce1a4f}">
      <Declaration><![CDATA[METHOD Send : BOOL
VAR_INPUT
	sTxData		: T_MaxString;	(* Data to send *)
END_VAR
VAR
	RTRIG_SendCommand			: R_TRIG;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[		fbTx.AddTail( sPut := sTxData );(* Put string to the tx fifo *)
		]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_EthDevice">
      <LineId Id="187" Count="7" />
      <LineId Id="107" Count="0" />
    </LineIds>
    <LineIds Name="FB_EthDevice.A_Receive">
      <LineId Id="2" Count="2" />
      <LineId Id="19" Count="4" />
      <LineId Id="18" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_EthDevice.Send">
      <LineId Id="9" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>