<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_DeletePartProgram" Id="{85ed054c-cb8a-4f09-a83a-a46cb0b7417c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DeletePartProgram 
VAR_INPUT
	Execute 	: BOOL;
	sNetId		: STRING;
	sPathName	: STRING;
	filesList   : ARRAY[0..99] OF STRING;
	filesNumb	: UINT;
END_VAR
VAR_OUTPUT
	Busy : BOOL;
	Done : BOOL;
	Error : BOOL;
	ErrorID : DINT;
	ErrorSubID : UDINT;
END_VAR
VAR
	iState : DINT := -1;
	i : USINT;
	fbFileDelete: FB_FileDelete;
	RTRIG_Execute : R_TRIG;
	TON_Timeout		: TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TON_Timeout(IN := Busy, PT := T#20S);
IF TON_Timeout.Q THEN
	
	iState := 1999;
END_IF

RTRIG_Execute(CLK := Execute);
IF(RTRIG_Execute.Q) THEN
	Done := FALSE;
	i := 0;
	ErrorID := 0;
	ErrorSubID := 0;
	
	iState := 0;
ELSIF NOT Execute AND NOT Busy THEN
	Busy			:= FALSE;
	Done			:= FALSE;
	Error			:= FALSE;
	
	iState := -1;
END_IF

CASE iState OF
	-1:
		;
	0:
		Busy := TRUE;
		fbFileDelete.sPathName := CONCAT(sPathName,filesList[i]);
		iState := 10;
		
	10:
		fbFileDelete.bExecute := TRUE;
		iState := 20;
			
	20:
        fbFileDelete.bExecute := FALSE; 
        IF NOT fbFileDelete.bBusy THEN 
        	IF fbFileDelete.bError THEN 
            	ErrorSubID := fbFileDelete.nErrId; 
                iState := 1020;
               ELSE 
                 	iState := 30;
               END_IF 
          END_IF
		  
	30:
		i := i + 1;
		IF i < filesNumb AND i <= 99 THEN
			iState := 0;
		ELSE
			iState := 999;
		END_IF

	999:
		Busy	 			:= FALSE;
		Done				:= TRUE;
	
		iState := -1;	
END_CASE

IF(iState > 999) THEN
	Error 	:= TRUE;
	ErrorID := iState;
	Busy 	:= FALSE;
ELSE
	Error := FALSE;
END_IF

A_Call();]]></ST>
    </Implementation>
    <Action Name="A_Call" Id="{e1f42e70-5a41-4d5e-a93a-04ed5770413c}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"FB_FileDelete"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"fbFileDelete"</v>
                          <v n="Type">"FB_FileDelete"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">66L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">29L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">30L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sNetId"</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">33L</v>
                            </o>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">35L</v>
                            </o>
                            <v n="Id">34L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"PATH_GENERIC"</v>
                              <v n="Type">"E_OPENPATH"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">37L</v>
                            </o>
                            <v n="Id">36L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">39L</v>
                            </o>
                            <v n="Id">38L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#5s"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">41L</v>
                            </o>
                            <v n="Id">40L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>sNetId</v>
                            <v>sPathName</v>
                            <v>ePath</v>
                            <v>bExecute</v>
                            <v>tTimeout</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>T_AmsNetId</v>
                            <v>T_MaxString</v>
                            <v>E_OpenPath</v>
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>bBusy</v>
                            <v>bError</v>
                            <v>nErrId</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">67L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">26L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="FB_DeletePartProgram">
      <LineId Id="214" Count="0" />
      <LineId Id="221" Count="2" />
      <LineId Id="212" Count="1" />
      <LineId Id="11" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="128" Count="0" />
      <LineId Id="187" Count="0" />
      <LineId Id="203" Count="0" />
      <LineId Id="205" Count="0" />
      <LineId Id="204" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="206" Count="5" />
      <LineId Id="47" Count="1" />
      <LineId Id="9" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="123" Count="0" />
      <LineId Id="192" Count="0" />
      <LineId Id="49" Count="0" />
      <LineId Id="188" Count="3" />
      <LineId Id="22" Count="1" />
      <LineId Id="26" Count="3" />
      <LineId Id="31" Count="1" />
      <LineId Id="34" Count="1" />
      <LineId Id="24" Count="0" />
      <LineId Id="194" Count="1" />
      <LineId Id="199" Count="0" />
      <LineId Id="196" Count="1" />
      <LineId Id="200" Count="1" />
      <LineId Id="198" Count="0" />
      <LineId Id="73" Count="0" />
      <LineId Id="71" Count="0" />
      <LineId Id="124" Count="1" />
      <LineId Id="182" Count="0" />
      <LineId Id="181" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="127" Count="0" />
      <LineId Id="126" Count="0" />
      <LineId Id="68" Count="1" />
      <LineId Id="67" Count="0" />
      <LineId Id="92" Count="0" />
      <LineId Id="50" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>